server:
  port: 8081 # El micro de tracking usará el 8082

spring:
  application:
    name: scraper
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer