openapi: 3.0.3
info:
  title: Game Scraper API
  version: 1.0.0
paths:
  /api/v1/scrape:
    post:
      summary: Dispara el scraping por pagina y plataforma (opcional)
      tags:
        - ScrapingController
      operationId: scrapePost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScrapePageRequestDto'
      responses:
        '200':
          description: Scraping aceptado y procesándose
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScrapeResponseDto'

components:
  schemas:
    ScrapePageRequestDto:
      type: object
      properties:
        page:
          type: integer
          format: int32
          example: "2"
        platform:
          $ref: '#/components/schemas/PlatformDto'
    ScrapeResponseDto:
      type: object
      properties:
        game:
          $ref: '#/components/schemas/GameDto'
        shopPriceInfo:
          $ref: '#/components/schemas/ShopPriceInfoDto'
    PlatformDto:
      type: string
      enum: [PC, PS5]
    GameDto:
      type: object
      properties:
        title:
          type: string
          example: "Elden Ring"
    ShopPriceInfoDto:
      type: object
      properties:
        shopName:
          type: string
          example: "InstantGaming"
        shopUri:
          type: string
          format: uri
          example: "www.instantgaming.es/game/elden-ring"
        price:
          type: number
          format: double
